# Generated by Django 3.0.6 on 2020-05-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('condition', models.TextField()),
                ('first_choice', models.CharField(max_length=100)),
                ('second_choice', models.CharField(max_length=100)),
                ('third_choice', models.CharField(max_length=100)),
                ('fourth_choice', models.CharField(max_length=100)),
                ('introduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Introduction')),
            ],
        ),
    ]
