# Generated by Django 3.0.6 on 2020-06-08 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('score', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('condition', models.TextField()),
                ('first_choice', models.CharField(max_length=100)),
                ('second_choice', models.CharField(max_length=100)),
                ('third_choice', models.CharField(max_length=100)),
                ('fourth_choice', models.CharField(max_length=100)),
                ('fifth_choice', models.CharField(max_length=100)),
                ('right_choice', models.CharField(choices=[('FIRST_CHOICE', 'first_choice'), ('SECOND_CHOICE', 'second_choice'), ('THIRD_CHOICE', 'third_choice'), ('FOURTH_CHOICE', 'fourth_choice'), ('FIFTH_CHOICE', 'fifth_choic')], default=models.CharField(max_length=100), max_length=100)),
                ('introduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='questions.Introduction')),
            ],
        ),
    ]
