# Generated by Django 3.0.7 on 2020-06-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.RenameField(
            model_name='introduction',
            old_name='score',
            new_name='option',
        ),
        migrations.RemoveField(
            model_name='introduction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='introduction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='introduction',
            name='number',
        ),
        migrations.AddField(
            model_name='introduction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='introduction',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='introduction',
            name='time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='introduction',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
    ]
