# Generated by Django 3.0.7 on 2020-06-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200607_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='image',
        ),
        migrations.RemoveField(
            model_name='introduction',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='introduction',
            name='time',
        ),
        migrations.RemoveField(
            model_name='introduction',
            name='title',
        ),
    ]
