# Generated by Django 3.0.6 on 2020-06-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200531_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='right_choice',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
