# Generated by Django 3.0.6 on 2020-06-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200608_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='introduction',
            old_name='score',
            new_name='балл',
        ),
        migrations.RenameField(
            model_name='introduction',
            old_name='description',
            new_name='введение',
        ),
        migrations.RenameField(
            model_name='introduction',
            old_name='name',
            new_name='имя',
        ),
        migrations.RenameField(
            model_name='introduction',
            old_name='number',
            new_name='номер',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='fifth_choice',
            new_name='a_вариант',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='first_choice',
            new_name='б_вариант',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='fourth_choice',
            new_name='в_вариант',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='introduction',
            new_name='введение',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='second_choice',
            new_name='г_вариант',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='third_choice',
            new_name='д_вариант',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='number',
            new_name='номер',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='explanation',
            new_name='объяснение',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='condition',
            new_name='условие',
        ),
        migrations.RemoveField(
            model_name='question',
            name='right_choice',
        ),
        migrations.AddField(
            model_name='question',
            name='правильный_вариант',
            field=models.CharField(choices=[('а_вариант', 'А_ВАРИАНТ'), ('б_вариант', 'Б_ВАРИАНТ'), ('в_вариант', 'В_ВАРИАНТ'), ('г_вариант', 'Г_ВАРИАНТ'), ('д_вариант', 'Д_ВАРИАНТ')], default=models.CharField(blank=True, max_length=100, null=True), max_length=100),
        ),
    ]
