# Generated by Django 3.0.6 on 2020-06-10 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20200608_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='правильный_вариант',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('правильный_вариант', models.CharField(choices=[('а_вариант', 'А_ВАРИАНТ'), ('б_вариант', 'Б_ВАРИАНТ'), ('в_вариант', 'В_ВАРИАНТ'), ('г_вариант', 'Г_ВАРИАНТ'), ('д_вариант', 'Д_ВАРИАНТ')], max_length=100)),
                ('отмеченный_ответ', models.CharField(blank=True, choices=[('а_вариант', 'А_ВАРИАНТ'), ('б_вариант', 'Б_ВАРИАНТ'), ('в_вариант', 'В_ВАРИАНТ'), ('г_вариант', 'Г_ВАРИАНТ'), ('д_вариант', 'Д_ВАРИАНТ')], max_length=100, null=True)),
                ('обЪяснение', models.TextField(blank=True, null=True)),
                ('вопрос', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='questions.Question')),
            ],
        ),
    ]
