# Generated by Django 3.0.6 on 2020-06-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20200610_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='обЪяснение',
            new_name='объяснение',
        ),
    ]
