# Generated by Django 3.0.6 on 2020-06-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20200610_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='отмеченный_ответ',
            new_name='отмеченный_вариант',
        ),
    ]
