# Generated by Django 3.0.6 on 2020-06-14 19:39

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_question_картинка'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='a_вариант',
            field=mdeditor.fields.MDTextField(blank=True, max_length=100, null=True),
        ),
    ]
