# Generated by Django 3.0.6 on 2020-06-15 11:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20200615_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='a_вариант',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
