# Generated by Django 3.0.6 on 2020-06-15 18:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20200615_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='б_вариант',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='в_вариант',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='г_вариант',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='д_вариант',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='объяснение',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='условие',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
