# Generated by Django 3.0.6 on 2020-06-16 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0013_auto_20200616_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='объяснение',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='правильный_вариант',
        ),
        migrations.AddField(
            model_name='question',
            name='правильный_вариант',
            field=models.CharField(blank=True, choices=[('а_вариант', 'А_ВАРИАНТ'), ('б_вариант', 'Б_ВАРИАНТ'), ('в_вариант', 'В_ВАРИАНТ'), ('г_вариант', 'Г_ВАРИАНТ'), ('д_вариант', 'Д_ВАРИАНТ')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('введение', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.Introduction')),
                ('ответы', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='questions.Answer')),
                ('пользователь', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
