# Generated by Django 3.0.6 on 2020-06-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20200616_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='правильный_вариант',
            field=models.CharField(choices=[('а_вариант', 'А_ВАРИАНТ'), ('б_вариант', 'Б_ВАРИАНТ'), ('в_вариант', 'В_ВАРИАНТ'), ('г_вариант', 'Г_ВАРИАНТ'), ('д_вариант', 'Д_ВАРИАНТ')], max_length=100),
        ),
    ]
