# Generated by Django 3.0.6 on 2020-06-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20200616_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='балл',
        ),
        migrations.AddField(
            model_name='review',
            name='балл',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
