# Generated by Django 3.0.6 on 2020-06-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20200616_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ответы',
        ),
        migrations.AddField(
            model_name='review',
            name='ответы',
            field=models.ManyToManyField(to='questions.Answer'),
        ),
    ]
