# Generated by Django 3.0.6 on 2020-06-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_auto_20200616_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='введение',
        ),
        migrations.AddField(
            model_name='review',
            name='введение',
            field=models.ManyToManyField(to='questions.Introduction'),
        ),
    ]
