# Generated by Django 3.0.6 on 2020-06-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_auto_20200617_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='вопрос',
        ),
        migrations.AddField(
            model_name='answer',
            name='вопрос',
            field=models.ManyToManyField(related_name='answer', to='questions.Question'),
        ),
    ]
