# Generated by Django 3.0.6 on 2020-06-16 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_auto_20200617_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ответы',
        ),
        migrations.AddField(
            model_name='answer',
            name='просмотр',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='questions.Review'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='вопрос',
            field=models.ManyToManyField(to='questions.Question'),
        ),
    ]
