# Generated by Django 3.0.6 on 2020-06-16 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_auto_20200617_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='вопрос',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='просмотр',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='questions.Review'),
        ),
    ]
